create table if not exists public.users (
    id integer generated by default as identity primary key,
    username varchar not null unique,
    password_hash varchar,
    gold integer not null default 0,
    daily_streak integer not null default 0,
    ecoling_state varchar not null default 'neutral',
    last_completed_date date,
    preferences jsonb not null default '{}'::jsonb,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists ix_users_id on public.users (id);

create table if not exists public.sessions (
    id integer generated by default as identity primary key,
    token_hash varchar not null unique,
    user_id integer not null references public.users(id),
    expires_at timestamp without time zone not null,
    created_at timestamp without time zone not null default (now() at time zone 'utc')
);

create index if not exists ix_sessions_id on public.sessions (id);
create index if not exists ix_sessions_token_hash on public.sessions (token_hash);
create index if not exists ix_sessions_user_id on public.sessions (user_id);

create table if not exists public.daily_quests (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id),
    quest_date date not null,
    quest_key varchar not null,
    quest_payload jsonb not null,
    weather_snapshot jsonb not null,
    completed boolean not null default false,
    completed_at timestamp without time zone,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    constraint uq_user_daily_quest unique (user_id, quest_date)
);

create index if not exists ix_daily_quests_id on public.daily_quests (id);
create index if not exists ix_daily_quests_user_id on public.daily_quests (user_id);
create index if not exists ix_daily_quests_quest_date on public.daily_quests (quest_date);

create table if not exists public.quest_slots (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id),
    slot_start timestamp without time zone not null,
    slot_end timestamp without time zone not null,
    quest_options jsonb not null,
    weather_snapshot jsonb not null,
    completed boolean not null default false,
    selected_quest_key varchar,
    completed_at timestamp without time zone,
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    constraint uq_user_quest_slot unique (user_id, slot_start)
);

create index if not exists ix_quest_slots_id on public.quest_slots (id);
create index if not exists ix_quest_slots_user_id on public.quest_slots (user_id);
create index if not exists ix_quest_slots_slot_start on public.quest_slots (slot_start);

create table if not exists public.friendships (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id),
    friend_id integer not null references public.users(id),
    created_at timestamp without time zone not null default (now() at time zone 'utc'),
    constraint uq_user_friend unique (user_id, friend_id)
);

create index if not exists ix_friendships_user_id on public.friendships (user_id);
create index if not exists ix_friendships_friend_id on public.friendships (friend_id);
